formal_iac/formal_iac/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('playbooks_parser.urls')),
]

formal_iac/playbooks_parser/urls.py
from django.urls import path

from . import views

app_name = 'playbooks_parser'
urlpatterns = [
    # ex: /playbooks_parser/
    path('', views.index_view, name='index_view'),
    # ex: /playbooks_parser/5
    path('<int:playbook_id>', views.playbook_view, name='playbook_view'),
    # ex: /playbooks_parser/5/parsed/
    path('<int:playbook_id>/parsed/', views.playbook_parsed_view, name='playbook_parsed_view'),
    # ex: /select_analysis
    path('select_analysis', views.select_analysis_view, name='select_analysis_view'),
    # ex: /demo
    path('demo', views.demo_view, name='demo_view'),
    # ex: /demo_result_view
    path('demo_result', views.demo_result_view, name='demo_result_view')
]

formal_iac/playbooks_parser/models.py
from django.db import models


class Vulnerability(models.Model):
    cve = models.CharField(max_length=200)
    cve_url = models.URLField()
    impact = models.CharField(max_length=50)

    def __str__(self):
        return self.cve


class Package(models.Model):
    package_name = models.CharField(max_length=200)
    set_of_vulnerabilities = models.ManyToManyField(Vulnerability)

    def __str__(self):
        return self.package_name


class State(models.Model):
    state_name = models.CharField(max_length=200)
    set_of_packages = models.ManyToManyField(Package)

    def __str__(self):
        return self.state_name


class PlaybookExecution(models.Model):
    execution_id = models.CharField(max_length=200)
    list_of_states = models.ManyToManyField(State)

    def __str__(self):
        return self.execution_id


class Task(models.Model):
    task_name = models.CharField(max_length=200)
    task_module = models.CharField(max_length=200)
    # module_arguments should be a list of strings for each option
    module_options = models.CharField(max_length=200)
    # module_arguments should be a list of strings for each argument
    module_arguments = models.CharField(max_length=200)

    def __str__(self):
        return self.task_name


class Playbook(models.Model):
    playbook_name = models.CharField(max_length=200)
    # Text Field instead of Charfield as it is potentially a huge amount of characters
    playbook_content = models.TextField()
    list_of_tasks = models.ManyToManyField(Task)

    def __str__(self):
        return self.playbook_name

formal_iac/playbooks_parser/forms.py
from django import forms

AVAILABLE_ANALYSES = [('0', 'Vulnerability Analysis'),
                      ('1', 'Example Analysis 1'),
                      ('2', 'Example Analysis 2'),
                      ('3', 'Example Analysis 3')]


class SelectAnalysisForm(forms.Form):
    available_analyses = forms.ChoiceField(label='Select an analysis to apply', widget=forms.RadioSelect,
                                           choices=AVAILABLE_ANALYSES, required=True)


EXAMPLE_PLAYBOOKS = [('0', 'Upload your own playbook'),
                     ('1', 'Install python and wget'),
                     ('2', 'Install httpd and nginx')]


class ParsePlaybookDemoForm(forms.Form):
    playbook_examples = forms.ChoiceField(label='Parse a playbook example', widget=forms.RadioSelect,
                                          choices=EXAMPLE_PLAYBOOKS, required=True)
    uploaded_playbook = forms.FileField(label='Upload your own playbook', required=False)

formal_iac/playbooks_parser/views.py
# views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect

from .auxiliary_functions import build_fsm_from_execution, create_playbook, create_playbook_execution
from .forms import ParsePlaybookDemoForm, SelectAnalysisForm
from .models import Playbook

from graphviz import Digraph
import yaml


def index_view(request):
    template = loader.get_template("playbooks_parser/index.html")
    return HttpResponse(template.render({}, request))


def playbook_view(request, playbook_id):
    requested_playbook = get_object_or_404(Playbook, pk=playbook_id)
    context = {
        'requested_ṕlaybook': requested_playbook,
    }
    return render(request, 'playbooks_parser/playbook.html', {'requested_playbook' : requested_playbook})


def playbook_parsed_view(request, playbook_id):
    requested_playbook = get_object_or_404(Playbook, pk=playbook_id)
    parsed_playbook = yaml.load(requested_playbook.playbook_content)
    context = {
        'parsed_playbook': parsed_playbook,
    }
    return render(request, 'playbooks_parser/parsed_playbook.html', {'parsed_playbook': parsed_playbook})


def select_analysis_view(request):
    if request.method == 'POST':
        return redirect('/demo')
    else:
        form = SelectAnalysisForm()
        context = {
            'form': form
        }
        return render(request, 'playbooks_parser/select_analysis.html', context)


def demo_view(request):
    form = ParsePlaybookDemoForm()
    context = {
        'form': form
    }
    return render(request, 'playbooks_parser/demo.html', context)


def demo_result_view(request):
    if request.method == 'POST':
        # Retrieve posted information
        form = ParsePlaybookDemoForm(request.POST, request.FILES)
        if form.is_valid():
            # Form validation, create/retrieve the playbook to analyze
            if form.cleaned_data['playbook_examples'] == '0' and form.cleaned_data['uploaded_playbook'] is not None:
                playbook_to_analyze = create_playbook(form.cleaned_data['uploaded_playbook'])
            elif form.cleaned_data['playbook_examples'] != '0':
                playbook_to_analyze = Playbook.objects.get(pk=form.cleaned_data['playbook_examples'])
            else:
                playbook_to_analyze = ""

            # Begin the analysis
            # With the playbook created/retrieved access its content and analyze the packages to be installed
            if playbook_to_analyze != "":
                playbook_execution = create_playbook_execution(playbook_to_analyze)
                fsm_representing_execution = build_fsm_from_execution(playbook_execution, playbook_to_analyze)
            else:
                fsm_representing_execution = []
            context = {
                # 'playbook_tasks': list_of_tasks,
                'execution_graph': fsm_representing_execution,
                'playbook_execution': playbook_execution
            }
            return render(request, "playbooks_parser/demo_result.html", context)
    return {}

formal_iac/playbooks_parser/templates/playbooks_parser/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>System Demo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'playbooks_parser/style.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <a href="{% url 'playbooks_parser:index_view' %}" class="nav-item">
                <img src="{% static 'playbooks_parser/dtu_logo.jpg' %}" width="40" height="40">
            </a>
            <a href="{% url 'playbooks_parser:demo_view' %}" class="nav-item"> Demo </a>
            <a href="/admin" class="nav-item"> Admin </a>
        </nav>
        <div class="row">
            <div class="col">
                <form enctype="multipart/form-data" method="post" action="{% url 'playbooks_parser:demo_result_view' %}">
                    {% csrf_token %}
                    {{ form }} <br> <br>
                    <input type="submit" value="Analyze Playbook">
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

formal_iac/playbooks_parser/templates/playbooks_parser/demo_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>System Demo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'playbooks_parser/style.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <a href="{% url 'playbooks_parser:index_view' %}" class="nav-item">
                <img src="{% static 'playbooks_parser/dtu_logo.jpg' %}" width="40" height="40">
            </a>
            <a href="{% url 'playbooks_parser:select_analysis_view' %}" class="nav-item"> Demo </a>
            <a href="/admin" class="nav-item"> Admin </a>
        </nav>
        <div class="row">
            <!-- This paragraph will be filled with the parsed playbook -->
            {% if execution_graph %}
            <div class="col-md-8 parsed-playbook">
                <br>
                    <p> Your playbook contains the following tasks </p>
                    {{ execution_graph|safe }}
            </div>
            <!-- Maybe include the state graph as well? -->
            <div class="col-md-4">
                <!-- If the request to parse the playbook has been done then display this paragraph -->
                <div>
                    {% if playbook_execution %}
                    <p>
                    The execution of your playbook will introduce the following vulnerabilities into your system:
                    </p>
                    <ul>
                        {% for state in playbook_execution.list_of_states.all %}
                        <li> {{ state.state_name }}:
                            {% for package in state.set_of_packages.all %}
                            {% if package.set_of_vulnerabilities.all %}
                            <ul>
                                <li> {{ package.package_name }}:
                                    <ul>
                                    {% for vulnerability in package.set_of_vulnerabilities.all %}
                                        <li><a href="{{ vulnerability.cve_url }}">{{ vulnerability.cve }}</a>  Impact: {{ vulnerability.impact }}</li>
                                    {% endfor %}
                                    </ul>
                                </li>
                            </ul>
                            {% endif %}
                            {% endfor %}
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p> Congrats! Your playbook does not contain any vulnerable package! </p>
                    {% endif %}
                </div>
            </div>
            {% else %}
            <p> Ops! it seems you tried to parse an empty playbook </p>
            {% endif %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

formal_iac/playbooks_parser/templates/playbooks_parser/graph.html
<!DOCTYPE html>
<meta charset="utf-8">
<body>
    {{ rendered_state|safe }}
</body>
</html>

formal_iac/playbooks_parser/templates/playbooks_parser/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>System Demo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'playbooks_parser/style.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <a href="{% url 'playbooks_parser:index_view' %}" class="nav-item">
                <img src="{% static 'playbooks_parser/dtu_logo.jpg' %}" width="40" height="40">
            </a>
            <a href="{% url 'playbooks_parser:select_analysis_view' %}" class="nav-item"> Demo </a>
            <a href="/admin" class="nav-item"> Admin </a>
        </nav>
        <h1> Formal Verification and Static Analysis of Infrastructure as Code Environments </h1>
        <br>
        <p>
            Code linting, compilers, static and dynamic analysis...nowadays software development  makes use of several
            tools that by formal methods, aim at improving the security and reliability of our systems. However,
            in this new paradigm where Infrastructure as a Code and configuration management has irrupted in modern
            organizations, the formal verification field has not been as developed as in its pure software homologous.
        </p>
        <br>
        <p>
            This project establishes an analysis framework for the study of security properties on Infrastructure as
            Code scripts for Ansible. This framework is based in finite state machines that allows to consider
            intermediate execution states and the impact these have on the properties of the host where the script is
            being run. We provide a specific example of a use case of this analysis framework by studying the process
            of package management and how the different possible states can introduce vulnerabilities in the system.
            For this analysis we follow a qualitative approach by using well-known sources of intelligence regarding
            vulnerability management
        </p>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

formal_iac/playbooks_parser/templates/playbooks_parser/playbook.html
<h1>{{ requested_playbook.playbook_name }}</h1>
<ul>
{% for task in requested_playbook.list_of_tasks.all %}
    <li>{{ task.task_name }}</li>
{% endfor %}
</ul>

formal_iac/playbooks_parser/templates/playbooks_parser/playbook_parsed.html
{{ parsed_playbook }}

formal_iac/playbooks_parser/templates/playbooks_parser/select_analysis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>System Demo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'playbooks_parser/style.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <a href="{% url 'playbooks_parser:index_view' %}" class="nav-item">
                <img src="{% static 'playbooks_parser/dtu_logo.jpg' %}" width="40" height="40">
            </a>
            <a href="{% url 'playbooks_parser:select_analysis_view' %}" class="nav-item"> Demo </a>
            <a href="/admin" class="nav-item"> Admin </a>
        </nav>

        <div class="row">
            <div class="col">
                <form enctype="multipart/form-data" method="post" action="{% url 'playbooks_parser:select_analysis_view' %}">
                    {% csrf_token %}
                    {{ form }} <br> <br>
                    <input type="submit" value="Try the selected Analysis">
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

formal_iac/playbooks_parser/templates/playbooks_parser/state.html
{% if latest_question_list %}
    <ul>
    {% for state in states_list %}
        <li><a href="/playbooks_parser/{{ state.id }}/">{{ state.state_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No states are available.</p>
{% endif %}